### ISSUE TITLE
typo in the chi2 calculation

### ISSUE THREAD

**Issue by mmikhasenko** [dwinney/kt-3pi#5]
The variable `tmp2` in the chi2 code seems to be commented by mistake
https://github.com/dwinney/kt-3pi/blob/master/src/param_fit.cpp#L212

it leads to the fact that `chi2=0` and fit does not work.
When the line 212 is uncommented, the script Omega_BW works as expected.

I suggest to avoid using pre-initiated scalar variables (`tmp1`, `tmp2`, `tmp3`, before the loop). You can create this variables in the loop. It works without any overhead since the compiler takes care of optimization anyway.

**Comment by dwinney** [comment]
Youre right, I'm not sure how that happened. The type is fixed now though! Everything should work now
